language: node_js
cache:
  directories:
    - node_modules
env:
  - MONGO_URI=mongodb://127.0.0.1:27017/netsblox-tests ENV=test
addons:
  apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - g++-4.8
services:
  - mongodb
node_js:
  - '8.11.2'
# install:
#   - cd .server; npm install
# before_script:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
script:
  - bash bin/test.sh
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
