/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function translate_musicxml(a: number, b: number): Array;
export function translate_midi(a: number, b: number): Array;
export function __wbg_timesignature_free(a: number, b: number): void;
export function __wbg_get_timesignature_signature(a: number): number;
export function __wbg_set_timesignature_signature(a: number, b: number): void;
export function __wbg_get_timesignature_numerator(a: number): number;
export function __wbg_set_timesignature_numerator(a: number, b: number): void;
export function __wbg_get_timesignature_denominator(a: number): number;
export function __wbg_set_timesignature_denominator(a: number, b: number): void;
export function timesignature_new(a: number): number;
export function timesignature_new_explicit(a: number, b: number): number;
export function __wbg_key_free(a: number, b: number): void;
export function __wbg_get_key_mode(a: number): number;
export function __wbg_set_key_mode(a: number, b: number): void;
export function __wbg_get_key_signature(a: number): number;
export function __wbg_set_key_signature(a: number, b: number): void;
export function key_new(a: number, b: number): number;
export function key_from_fifths(a: number, b: number): number;
export function key_fifths(a: number): number;
export function key_to_parallel(a: number): number;
export function key_to_relative(a: number): number;
export function key_make_parallel(a: number): void;
export function key_make_relative(a: number): void;
export function __wbg_clef_free(a: number, b: number): void;
export function __wbg_get_clef_symbol(a: number): number;
export function __wbg_set_clef_symbol(a: number, b: number): void;
export function __wbg_get_clef_clef_type(a: number): number;
export function __wbg_set_clef_clef_type(a: number, b: number): void;
export function clef_new(a: number, b: number): number;
export function __wbg_pitch_free(a: number, b: number): void;
export function __wbg_get_pitch_name(a: number): number;
export function __wbg_set_pitch_name(a: number, b: number): void;
export function __wbg_get_pitch_octave(a: number): number;
export function __wbg_set_pitch_octave(a: number, b: number): void;
export function pitch_new(a: number, b: number): number;
export function pitch_new_rest(): number;
export function pitch_is_rest(a: number): number;
export function __wbg_temposuggestion_free(a: number, b: number): void;
export function __wbg_get_temposuggestion_marking(a: number): number;
export function __wbg_set_temposuggestion_marking(a: number, b: number): void;
export function temposuggestion_new(a: number): number;
export function temposuggestion_description(a: number): Array;
export function temposuggestion_bpm_min(a: number): number;
export function temposuggestion_bpm_max(a: number): number;
export function temposuggestion_value(a: number): number;
export function __wbg_duration_free(a: number, b: number): void;
export function __wbg_get_duration_value(a: number): number;
export function __wbg_set_duration_value(a: number, b: number): void;
export function __wbg_get_duration_dots(a: number): number;
export function __wbg_set_duration_dots(a: number, b: number): void;
export function duration_new(a: number, b: number): number;
export function duration_from_beats(a: number, b: number): number;
export function duration_from_duration(a: number, b: number): number;
export function duration_value(a: number): number;
export function duration_beats(a: number, b: number): number;
export function duration_split(a: number, b: number): number;
export function __wbg_tempo_free(a: number, b: number): void;
export function __wbg_get_tempo_base_note(a: number): number;
export function __wbg_set_tempo_base_note(a: number, b: number): void;
export function __wbg_get_tempo_beats_per_minute(a: number): number;
export function __wbg_set_tempo_beats_per_minute(a: number, b: number): void;
export function tempo_new(a: number, b: number): number;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_malloc(a: number, b: number): number;
export function __externref_table_dealloc(a: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_start(): void;
