name: Push Docker Hub

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  publish:

    strategy:
        matrix:
            os: [ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
        
      - name: Get Release Tags
        id: get_release_tags
        run: |
          echo "RELEASE_TAG=$(echo ${GITHUB_REF} | sed -E 's/.*v?([0-9]+)\.([0-9]+)\.([0-9]+)?/\1.\2.\3,\1.\2,\1/')" >> $GITHUB_ENV
          echo "TAG=latest" >> $GITHUB_ENV
        if: github.event_name == 'release'

      - name: Get Push Tags
        id: get_push_tags
        run: |
          echo "RELEASE_TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
          echo "TAG=nightly" >> $GITHUB_ENV
        if: github.event_name == 'push'
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            netsblox/browser:${{ env.TAG }}
            netsblox/browser${{ env.RELEASE_TAG }}
